secondary/config/routes.rb
Rails.application.routes.draw do
  resources :secondary_names
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "secondary_names#index"
end

secondary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

secondary/app/models/secondary_name.rb
class SecondaryName < ApplicationRecord
end

secondary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

secondary/app/controllers/secondary_names_controller.rb
class SecondaryNamesController < ApplicationController
  before_action :set_secondary_name, only: %i[ show edit update destroy ]

  # GET /secondary_names or /secondary_names.json
  def index
    @secondary_names = SecondaryName.all
  end

  # GET /secondary_names/1 or /secondary_names/1.json
  def show
  end

  # GET /secondary_names/new
  def new
    @secondary_name = SecondaryName.new
  end

  # GET /secondary_names/1/edit
  def edit
  end

  # POST /secondary_names or /secondary_names.json
  def create
    @secondary_name = SecondaryName.new(secondary_name_params)

    respond_to do |format|
      if @secondary_name.save
        format.html { redirect_to @secondary_name, notice: "Secondary name was successfully created." }
        format.json { render :show, status: :created, location: @secondary_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @secondary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /secondary_names/1 or /secondary_names/1.json
  def update
    respond_to do |format|
      if @secondary_name.update(secondary_name_params)
        format.html { redirect_to @secondary_name, notice: "Secondary name was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @secondary_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @secondary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secondary_names/1 or /secondary_names/1.json
  def destroy
    @secondary_name.destroy!

    respond_to do |format|
      format.html { redirect_to secondary_names_path, notice: "Secondary name was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secondary_name
      @secondary_name = SecondaryName.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def secondary_name_params
      params.expect(secondary_name: [ :name ])
    end
end

secondary/app/helpers/application_helper.rb
module ApplicationHelper
end

secondary/app/helpers/secondary_names_helper.rb
module SecondaryNamesHelper
end

secondary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Secondary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Secondary">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

secondary/app/views/secondary_names/_form.html.erb
<%= form_with(model: secondary_name) do |form| %>
  <% if secondary_name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(secondary_name.errors.count, "error") %> prohibited this secondary_name from being saved:</h2>

      <ul>
        <% secondary_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

secondary/app/views/secondary_names/_secondary_name.html.erb
<div id="<%= dom_id secondary_name %>">
  <div>
    <strong>Name:</strong>
    <%= secondary_name.name %>
  </div>

</div>

secondary/app/views/secondary_names/edit.html.erb
<% content_for :title, "Editing secondary name" %>

<h1>Editing secondary name</h1>

<%= render "form", secondary_name: @secondary_name %>

<br>

<div>
  <%= link_to "Show this secondary name", @secondary_name %> |
  <%= link_to "Back to secondary names", secondary_names_path %>
</div>

secondary/app/views/secondary_names/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Secondary names" %>

<h1>Secondary names</h1>

<div id="secondary_names">
  <% @secondary_names.each do |secondary_name| %>
    <%= render secondary_name %>
    <p>
      <%= link_to "Show this secondary name", secondary_name %>
    </p>
  <% end %>
</div>

<%= link_to "New secondary name", new_secondary_name_path %>


<hr>

<h1>Elm hello</h1>

<div id="elm">Loading Elm, please wait...</div>


<%
js_filename = 'hello.js'
js_file = File.join(Rails.root, 'public', js_filename)
js_mtime =File.mtime(js_file).to_i

flag_data = {nothing: ''}
%>
<script src="<%= "/#{js_filename}?#{js_mtime}" %>"></script>
<script>
 var app = Elm.Hello.init({ node: document.getElementById('elm'),
                            flags: <%= raw JSON.generate flag_data %>
 })
 // you can use ports and stuff here
</script>

secondary/app/views/secondary_names/new.html.erb
<% content_for :title, "New secondary name" %>

<h1>New secondary name</h1>

<%= render "form", secondary_name: @secondary_name %>

<br>

<div>
  <%= link_to "Back to secondary names", secondary_names_path %>
</div>

secondary/app/views/secondary_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @secondary_name %>

<div>
  <%= link_to "Edit this secondary name", edit_secondary_name_path(@secondary_name) %> |
  <%= link_to "Back to secondary names", secondary_names_path %>

  <%= button_to "Destroy this secondary name", @secondary_name, method: :delete %>
</div>