primary/config/routes.rb
Rails.application.routes.draw do
  resources :primary_names
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "primary_names#index"
end

primary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

primary/app/models/primary_name.rb
class PrimaryName < ApplicationRecord
end

primary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

primary/app/controllers/primary_names_controller.rb
class PrimaryNamesController < ApplicationController
  before_action :set_primary_name, only: %i[ show edit update destroy ]

  # GET /primary_names or /primary_names.json
  def index
    @primary_names = PrimaryName.all
  end

  # GET /primary_names/1 or /primary_names/1.json
  def show
  end

  # GET /primary_names/new
  def new
    @primary_name = PrimaryName.new
  end

  # GET /primary_names/1/edit
  def edit
  end

  # POST /primary_names or /primary_names.json
  def create
    @primary_name = PrimaryName.new(primary_name_params)

    respond_to do |format|
      if @primary_name.save
        format.html { redirect_to @primary_name, notice: "Primary name was successfully created." }
        format.json { render :show, status: :created, location: @primary_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @primary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /primary_names/1 or /primary_names/1.json
  def update
    respond_to do |format|
      if @primary_name.update(primary_name_params)
        format.html { redirect_to @primary_name, notice: "Primary name was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @primary_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @primary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primary_names/1 or /primary_names/1.json
  def destroy
    @primary_name.destroy!

    respond_to do |format|
      format.html { redirect_to primary_names_path, notice: "Primary name was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_primary_name
      @primary_name = PrimaryName.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def primary_name_params
      params.expect(primary_name: [ :name ])
    end
end

primary/app/helpers/application_helper.rb
module ApplicationHelper
end

primary/app/helpers/primary_names_helper.rb
module PrimaryNamesHelper
end

primary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Primary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Primary">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

primary/app/views/primary_names/_form.html.erb
<%= form_with(model: primary_name) do |form| %>
  <% if primary_name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(primary_name.errors.count, "error") %> prohibited this primary_name from being saved:</h2>

      <ul>
        <% primary_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

primary/app/views/primary_names/_primary_name.html.erb
<div id="<%= dom_id primary_name %>">
  <div>
    <strong>Name:</strong>
    <%= primary_name.name %>
  </div>

</div>

primary/app/views/primary_names/edit.html.erb
<% content_for :title, "Editing primary name" %>

<h1>Editing primary name</h1>

<%= render "form", primary_name: @primary_name %>

<br>

<div>
  <%= link_to "Show this primary name", @primary_name %> |
  <%= link_to "Back to primary names", primary_names_path %>
</div>

primary/app/views/primary_names/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Primary names" %>

<h1>Primary names</h1>

<div id="primary_names">
  <% @primary_names.each do |primary_name| %>
    <%= render primary_name %>
    <p>
      <%= link_to "Show this primary name", primary_name %>
    </p>
  <% end %>
</div>

<%= link_to "New primary name", new_primary_name_path %>

<hr>
<h3>Tried Links</h3>

<p>
  <a href="https://localhost">primary HTTPS</a>
</p>

<p>
  <a href="http://localhost:3000">primary http</a>
</p>

<p>
  <a href="https://localhost:5010/secondary">secondary HTTPS</a>
</p>

<p>
  <a href="http://localhost:3001">secondary http</a>
</p>

<hr>

<h1>Elm hello</h1>

<div id="elm">Loading Elm, please wait...</div>


<%
js_filename = 'hello.js'
js_file = File.join(Rails.root, 'public', js_filename)
js_mtime =File.mtime(js_file).to_i

flag_data = {nothing: ''}
%>
<script src="<%= "/#{js_filename}?#{js_mtime}" %>"></script>
<script>
 var app = Elm.Hello.init({ node: document.getElementById('elm'),
                            flags: <%= raw JSON.generate flag_data %>
 })
 // you can use ports and stuff here
</script>

primary/app/views/primary_names/new.html.erb
<% content_for :title, "New primary name" %>

<h1>New primary name</h1>

<%= render "form", primary_name: @primary_name %>

<br>

<div>
  <%= link_to "Back to primary names", primary_names_path %>
</div>

primary/app/views/primary_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @primary_name %>

<div>
  <%= link_to "Edit this primary name", edit_primary_name_path(@primary_name) %> |
  <%= link_to "Back to primary names", primary_names_path %>

  <%= button_to "Destroy this primary name", @primary_name, method: :delete %>
</div>