apiary/config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resource "hello", only: [:show]
    end
  end

  resources :apiary_names
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "apiary_names#index"
end

apiary/app/models/apiary_name.rb
class ApiaryName < ApplicationRecord
end

apiary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

apiary/app/controllers/api/v1/hellos_controller.rb
class Api::V1::HellosController < ApplicationController
  def show
    render json: { hello: "hello - it's #{Time.now}" }
  end
end

apiary/app/controllers/apiary_names_controller.rb
class ApiaryNamesController < ApplicationController
  before_action :set_apiary_name, only: %i[ show edit update destroy ]

  # GET /apiary_names or /apiary_names.json
  def index
    @apiary_names = ApiaryName.all
  end

  # GET /apiary_names/1 or /apiary_names/1.json
  def show
  end

  # GET /apiary_names/new
  def new
    @apiary_name = ApiaryName.new
  end

  # GET /apiary_names/1/edit
  def edit
  end

  # POST /apiary_names or /apiary_names.json
  def create
    @apiary_name = ApiaryName.new(apiary_name_params)

    respond_to do |format|
      if @apiary_name.save
        format.html { redirect_to @apiary_name, notice: "Apiary name was successfully created." }
        format.json { render :show, status: :created, location: @apiary_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apiary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apiary_names/1 or /apiary_names/1.json
  def update
    respond_to do |format|
      if @apiary_name.update(apiary_name_params)
        format.html { redirect_to @apiary_name, notice: "Apiary name was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @apiary_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apiary_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apiary_names/1 or /apiary_names/1.json
  def destroy
    @apiary_name.destroy!

    respond_to do |format|
      format.html { redirect_to apiary_names_path, notice: "Apiary name was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apiary_name
      @apiary_name = ApiaryName.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def apiary_name_params
      params.expect(apiary_name: [ :name ])
    end
end

apiary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

apiary/app/helpers/apiary_names_helper.rb
module ApiaryNamesHelper
end

apiary/app/helpers/application_helper.rb
module ApplicationHelper
end

apiary/app/views/apiary_names/_apiary_name.html.erb
<div id="<%= dom_id apiary_name %>">
  <div>
    <strong>Name:</strong>
    <%= apiary_name.name %>
  </div>

</div>

apiary/app/views/apiary_names/_form.html.erb
<%= form_with(model: apiary_name) do |form| %>
  <% if apiary_name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(apiary_name.errors.count, "error") %> prohibited this apiary_name from being saved:</h2>

      <ul>
        <% apiary_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

apiary/app/views/apiary_names/edit.html.erb
<% content_for :title, "Editing apiary name" %>

<h1>Editing apiary name</h1>

<%= render "form", apiary_name: @apiary_name %>

<br>

<div>
  <%= link_to "Show this apiary name", @apiary_name %> |
  <%= link_to "Back to apiary names", apiary_names_path %>
</div>

apiary/app/views/apiary_names/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Apiary names" %>

<h1>Apiary names</h1>

<div id="apiary_names">
  <% @apiary_names.each do |apiary_name| %>
    <%= render apiary_name %>
    <p>
      <%= link_to "Show this apiary name", apiary_name %>
    </p>
  <% end %>
</div>

<%= link_to "New apiary name", new_apiary_name_path %>

apiary/app/views/apiary_names/new.html.erb
<% content_for :title, "New apiary name" %>

<h1>New apiary name</h1>

<%= render "form", apiary_name: @apiary_name %>

<br>

<div>
  <%= link_to "Back to apiary names", apiary_names_path %>
</div>

apiary/app/views/apiary_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @apiary_name %>

<div>
  <%= link_to "Edit this apiary name", edit_apiary_name_path(@apiary_name) %> |
  <%= link_to "Back to apiary names", apiary_names_path %>

  <%= button_to "Destroy this apiary name", @apiary_name, method: :delete %>
</div>

apiary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Apiary" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Apiary">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>